- name: Setup Apache 
  hosts: all
  gather_facts: yes
  become: yes

  tasks:
  - name: Run  role
    import_role:
      name: apache2
  - name: test apache
    shell: curl {{ansible_hostname}}
    delegate_to: 127.0.0.1
    register: out
  - debug:
     msg: "{{ out.stdout }}"
