---
# tasks file for apache2
- name: Install Apache2
  package:
    name: "{{ apache_service }}" 
    state: "{{ apache_state }}"

- block: 
  - name: Configuring service 
    service:
      name: "{{ apache_service }}"
      state: started
      enabled: yes

  - name: Copy index test page
    template:
      src: "templates/index.html.j2"
      dest: "{{ apache_default_site }}/index.html"
    notify: Restart apache2
  when: apache_state == 'present'