---
# handlers file for apache2
- name: Reload Apache
  service:
    name: apache2
    state: reloaded

- name: Restart and enable the service
  service:
    name: apache2
    state: restarted
    enabled: yes

