---
- name: The demo playbook
  hosts: all
  gather_facts: yes

  tasks:
    - name: Get the current user
      shell: whoami
      register: myUser

    - name: Display the current user
      debug:
        msg: "The current user is {{ myUser.stdout }} "