---
- name: The demo playbook
  hosts: all
  gather_facts: yes
  become: yes # true = yes / false = no

  tasks:
    - name: create multiple directories
      file:
        path: "{{ item }}"
        state: directory
        owner: root
        group: root
        mode: 0775
      loop:
        - /tmp/a
        - /tmp/b
        - /tmp/c
      
      when: ansible_os_family == 'Debian'