---
- name: The demo playbook
  hosts: all
  gather_facts: yes
  become: yes # true = yes / false = no

  tasks:
    - name: remove multiple directories
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /tmp/a
        - /tmp/b
        - /tmp/c
      
      when: ansible_os_family == 'RedHat'
