# Playbook for automated apache installation
---
- name: The demo playbook
  hosts: all
  gather_facts: yes

  tasks:
    - name: Copy script over to linux nodes
      copy:
        src: index.html
        dest: /tmp/
        mode: 0755

    # - name: Running dummy script
    #   shell: /tmp/dummy.sh