# Playbook for automated apache installation
---
- name: The demo playbook
  hosts: all
  gather_facts: yes

  tasks:
    - name: Install Apache package
      apt:
        name: apache2
        state: latest

    - name: Restart and enable the service
      systemd:
        name: apache2
        state: restarted
        enabled: yes
