# Playbook for automated apache installation
---
- name: The Apche playbook
  hosts: centos
  become: yes

  vars_files:
    - vars/default.yml
  gather_facts: yes

  tasks:
    - name: Install Apache latest version
      yum:
        name: httpd
        state: latest
       
    - name: Create document root for your domain
      file:
        path: "/var/www/{{ http_host }}"
        state: directory
        mode: '0755'

    - name: Copy index page
      template:
        src: "templates/index.html.js"
        dest: "/var/www/{{ http_host }}/index.html"
    
    - name: Set up virtualHost
      template:
        src: "templates/httpd.conf.j2"
        dest: "/etc/httpd/conf.d/{{ http_host }}.conf"
      notify: Reload Apache
      
    - name: "Allow HTTP port on firewalld"
      firewalld:
        immediate: yes
        permanent: yes
        port: "{{ item }}/tcp"
        state: enabled
        zone: public
      loop:
        - "{{ http_port }}"
        - "{{ https_port }}"

  handlers:
    - name: Reload Apache
      service:
        name: httpd
        state: reloaded

    - name: Restart and enable the service
      service:
        name: httpd
        state: restarted
        enabled: yes
