all:
  hosts:
  children:
    linux:
      children:
        centos:
          hosts:
            centos01:
              ansible_host: 192.168.10.10

        ubuntu:
          hosts:
            ubuntu01:
              ansible_host: 192.168.10.21
