---
# tasks file for apache2
  - name: Install Apache for CentOS, RedHat, ...
    yum:
      name: httpd
      state: latest
    when: ansible_os_family == 'RedHat'

  - name: Install Apache for Ubuntu, Debian, ...
    apt:
      name: apache2
      state: latest
    when: ansible_os_family == 'Debian'

  - name: copy config file
    template:
      src: templates/index.html.j2
      dest: /var/www/html/index.html
      mode: 0755
      owner: root
    notify: restart web
