# site.yml
---
- name: Setup Apache web server
  hosts: all
  gather_facts: yes
  become: yes

  tasks:
   - name: Setup Apache using role
     import_role:
       name: apache2
  
   - name: Check the welcome page
     shell: cat /var/www/html/index.html
     register: result
     
   - name: Display welcome page
     debug:
       msg: "{{ result.stdout }}"
