---
- name: A simple play to demonstrate prompting in a playbook
  hosts: all

  vars_prompt:
    - name: loginid
      prompt: "Enter your username"
      private: no
    - name: password
      prompt: "Enter your password"
      private: yes

  tasks:
    - name: Proceed with login
      debug:
        msg: "Logging in as {{ loginid }} ..."


